remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
author: notaswe
title: notablog
description: [by notaswe]
github:
  repository_url: https://github.com/notaSWE/
url: "https://notaswe.github.io"
baseurl: "/notablog"
future: true